name: run
run_id: commands[0]
env COLUMNS: 280
env HOME: /home/ubuntu
env LANG: C.UTF-8
env LINES: 70
env PATH: /home/ubuntu/bankchurn-api/.tox/test_app/bin:/home/ubuntu/env-api/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONHASHSEED: 3608287415
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TERM: xterm-256color
env TOX_ENV_DIR: /home/ubuntu/bankchurn-api/.tox/test_app
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /home/ubuntu/bankchurn-api/.tox
env VIRTUAL_ENV: /home/ubuntu/bankchurn-api/.tox/test_app
metadata pid: 3762
cwd: /home/ubuntu/bankchurn-api
allow: /home/ubuntu/bankchurn-api/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: -15
[32mINFO[0m:     190.25.82.133:57777 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     190.25.82.133:57777 - "[1mGET /favicon.ico HTTP/1.1[0m" [31m404 Not Found[0m

standard error:
[32m2025-09-01 20:11:15.677[0m | [33m[1mWARNING [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [33m[1mRunning in development mode. Do not run like this in production.[0m
[32mINFO[0m:     Started server process [[36m3762[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8001[0m (Press CTRL+C to quit)
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m3762[0m]
[31mERROR[0m:    Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/usr/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/starlette/routing.py", line 701, in lifespan
    await receive()
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "/home/ubuntu/bankchurn-api/app/main.py", line 59, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8001, log_level="debug")
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/ubuntu/bankchurn-api/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/usr/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
